###### GET ALL ######
GET http://localhost:5000/api/users

###### CREATE ######
POST http://localhost:5000/api/users
Content-Type: application/json

{
	"companyContact": "Jimbob",
  "companyName": "ABC Corp",
  "contactMethod": "phone",
  "email": "f@t.com",
  "password": "password"
}

###### GET ONE ######
GET  http://localhost:5000/api/users/104

###### UPDATE ######
PATCH http://localhost:5000/api/users/2
Content-Type: application/json

{
	"companyContact": "Updated User",
  "companyName": "ABC Corp",
  "contactMethod": "phone",
  "email": "f@rt.com"
}

###### SOFT DELETE ######
DELETE  http://localhost:5000/api/users/101

###### HARD DELETE ######
DELETE http://localhost:5000/api/users/101/hard

###### GET ALL INCLUDING SOFT DELETED ######
GET http://localhost:5000/api/users/all

###### GET ALL WITH PARAMS ######
GET http://localhost:5000/api/users?search=f@t

###### GET COUNT ######
GET http://localhost:5000/api/users/count